version: '3'
services:
        app:
            build: .
            image: golang:1.11
            container_name: gomongoapp
            volumes:
              - .:/go/src/github.com/angadthandi/gomongo
            ports:
              - "9001:9001"
            working_dir: /go/src/github.com/angadthandi/gomongo
            command: bash -c "go get -v && go build && ./gomongo"
            depends_on:
                - mongodb
            links:
                - mongodb
        mongodb:
           build: .
           image: mongo:4.0
           container_name: gomongodb
           volumes:
             - .:/home/angadthandi/Documents/mongodbdata
           ports:
                   - "27017:27017"
